version: '3.7'

services:    
    php:
        volumes:
            - ${SYMFONY_APP_PATH}:/usr/src/app
    nginx:
        volumes:
            - ${SYMFONY_APP_PATH}public/:/usr/src/app
            - ${SYMFONY_APP_PATH}docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        ports:
            - ${NGINX_PORT}:80
    composer:
        volumes:
            - ${SYMFONY_APP_PATH}:/usr/src/app
    nodejs:
        volumes:
            - ${SYMFONY_APP_PATH}:/home/node/app