home_page:
    resource: './../src/Controller/PageController.php'
    type:     annotation
    prefix:   /
    
web_profile:
    resource: './../src/Controller/WebProfileController.php'
    type:     annotation
    prefix:   /profile
    
docs:
    resource: './../src/Controller/DocsController.php'
    type:     annotation
    prefix:   /docs